import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Kufi_Arabic } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'
import "./globals.css";
import Header from "@/components/header/Header"
import Footer from "@/components/Footer"
// @ sign it's an alias to src directory

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kufi = Noto_Kufi_Arabic({
  subsets: ['arabic'],
  weight: ['600']
});

export const metadata: Metadata = {
  title: "Next Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={kufi.className}
      >
        <Header />
        <ToastContainer theme='colored' position='top-center' />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
